In [1]:
import numpy as np


In [2]:
list=[1,2,3,4]
#mandatry arument list in array
numpy_array=np.array(list)
print(numpy_array)
print(type(numpy_array))


[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
#numpy array only contain homogenous element example:
list=[1,2,3,4,'a',0.5]
numpy_array=np.array(list)
print(numpy_array)
#iven below all are type of string

['1' '2' '3' '4' 'a' '0.5']


In [8]:
#you can type cast using one more arument:
list=[1,2,3,4,0.4,0.3]
numpy_array_new=np.array(list,dtype=int)
print(numpy_array_new)


[1 2 3 4 0 0]


In [9]:
list=[1,2,34,5]
numpy_array=np.array(list*3)
print(numpy_array)

[ 1  2 34  5  1  2 34  5  1  2 34  5]


In [11]:
np_full=np.full((3,4),7,dtype=float)
print(np_full)

[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]


In [12]:
#new topic to learn

In [15]:
np_arrange=np.arange(10)
print(np_arrange)


[0 1 2 3 4 5 6 7 8 9]


In [21]:
np_arrange=np.arange(1,10,2)
print(np_arrange)

[1 3 5 7 9]


In [24]:
np_liinespace=np.linspace(1,10,5,endpoint=False)
print(np_liinespace)

[1.  2.8 4.6 6.4 8.2]


In [26]:
matrix=np.identity(3,dtype=int)
print(matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [27]:
matrix=np.eye(3,4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [30]:
r=np.random.rand(10)*10
print(r)

[8.66673458 7.50090895 5.813089   2.96460861 6.19279839 8.9836019
 7.63788793 3.16680943 7.61809984 1.71093064]


In [34]:
#index and slicing
list=[1,2,3,4,5,6,7]
array=np.array(list)
print(array.data)
print(array.strides)
print(array.dtype)
print(array.shape)
print(array.sum())
print(array.mean())
print(array.max())
print(array.argmin())
print(array.argmax())

(4,)
int32
(7,)
28
4.0
7
0
6
